// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201106151201_ActivityEntity")]
    partial class ActivityEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Domain.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperetureC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemperetureF")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WeatherDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Weathers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Summary = "windy",
                            TemperetureC = 20,
                            TemperetureF = 50,
                            WeatherDate = new DateTime(2020, 11, 6, 18, 42, 0, 812, DateTimeKind.Local).AddTicks(5076)
                        },
                        new
                        {
                            Id = 2,
                            Summary = "fogy",
                            TemperetureC = 15,
                            TemperetureF = 30,
                            WeatherDate = new DateTime(2020, 11, 6, 18, 42, 0, 816, DateTimeKind.Local).AddTicks(110)
                        },
                        new
                        {
                            Id = 3,
                            Summary = "freezing",
                            TemperetureC = 5,
                            TemperetureF = 20,
                            WeatherDate = new DateTime(2020, 11, 6, 18, 42, 0, 816, DateTimeKind.Local).AddTicks(183)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
